//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cardbooru.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentSite {
            get {
                return ((string)(this["CurrentSite"]));
            }
            set {
                this["CurrentSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://danbooru.donmai.us")]
        public string DanbooruUrl {
            get {
                return ((string)(this["DanbooruUrl"]));
            }
            set {
                this["DanbooruUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://safebooru.org")]
        public string SafeBooruUrl {
            get {
                return ((string)(this["SafeBooruUrl"]));
            }
            set {
                this["SafeBooruUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/posts.json?limit=*&page=*/")]
        public string DanbooruPostsUrl {
            get {
                return ((string)(this["DanbooruPostsUrl"]));
            }
            set {
                this["DanbooruPostsUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/index.php?page=dapi&s=post&q=index&limit=*&pid=*&json=1")]
        public string SafeBooruPostsUrl {
            get {
                return ((string)(this["SafeBooruPostsUrl"]));
            }
            set {
                this["SafeBooruPostsUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int NumberOfPicPerRequest {
            get {
                return ((int)(this["NumberOfPicPerRequest"]));
            }
            set {
                this["NumberOfPicPerRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SafeCheck {
            get {
                return ((bool)(this["SafeCheck"]));
            }
            set {
                this["SafeCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuestionableCheck {
            get {
                return ((bool)(this["QuestionableCheck"]));
            }
            set {
                this["QuestionableCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExplicitCheck {
            get {
                return ((bool)(this["ExplicitCheck"]));
            }
            set {
                this["ExplicitCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UndefinedCheck {
            get {
                return ((bool)(this["UndefinedCheck"]));
            }
            set {
                this["UndefinedCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://gelbooru.com")]
        public string GelbooruSiteUrl {
            get {
                return ((string)(this["GelbooruSiteUrl"]));
            }
            set {
                this["GelbooruSiteUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/index.php?page=dapi&s=post&q=index&limit=*&pid=*&json=1")]
        public string GelbooruPostsUrl {
            get {
                return ((string)(this["GelbooruPostsUrl"]));
            }
            set {
                this["GelbooruPostsUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cache/image/")]
        public string PathToCacheFolder {
            get {
                return ((string)(this["PathToCacheFolder"]));
            }
            set {
                this["PathToCacheFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection BlackListTags {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BlackListTags"]));
            }
            set {
                this["BlackListTags"] = value;
            }
        }
    }
}
